### ISSUE TITLE
decrypt.sh should exit successfully if iv or key are empty strings.

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/travis#8]
To support pull requests from forked repos, we should allow decrypt.sh to exit without error when the key and iv values are empty strings.

**Comment by pboothe** [comment]
https://github.com/m-lab/annotation-service/blob/master/.travis.yml contains one workaround for this issue.

**Comment by kokosta** [comment]
To confirm the status.

**Comment by stephen-soltesz** [comment]
Fixed.
